# Generated by Django 5.2.17 on 2026-08-20 03:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('damaged', 'Damaged item'), ('missing', 'Missing item'), ('count_correction', 'Count correction'), ('admin_correction', 'Admin correction'), ('other', 'Other')], max_length=32)),
                ('quantity_delta', models.IntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_adjustments', to='canteen.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('restocked_on', models.DateField(default=django.utils.timezone.localdate)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entered_restocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-restocked_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('line_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='restock_items', to='canteen.inventoryitem')),
                ('restock_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='canteen.restockevent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RestockTaxLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=32)),
                ('rate_percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('was_applied', models.BooleanField(default=True)),
                ('restock_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_lines', to='canteen.restockevent')),
            ],
            options={
                'ordering': ['tax_name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('balance', 'Student Balance')], max_length=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('void', 'Void')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_sales', to=settings.AUTH_USER_MODEL)),
                ('student_tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='canteen.studenttab')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('load', 'Load'), ('purchase', 'Purchase'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=16)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('balance', 'Student Balance'), ('internal', 'Internal')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_balance_transactions', to=settings.AUTH_USER_MODEL)),
                ('student_tab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_transactions', to='canteen.studenttab')),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_transactions', to='canteen.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='canteen.inventoryitem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='canteen.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
