# Generated by Django 5.2.17 on 2026-09-12 02:56

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def require_nsid_login_for_existing_accounts(apps, schema_editor):
    Account = apps.get_model("canteen", "Account")
    if Account.objects.filter(user=None).exists():
        raise RuntimeError(
            "Migration 0004 cannot remove Student Number while unlinked accounts exist. "
            "This deployment contains test data only: delete/recreate those accounts or reset "
            "the test database, then run migrate again."
        )


def invalidate_legacy_customer_passwords(apps, schema_editor):
    Account = apps.get_model("canteen", "Account")
    for account in Account.objects.select_related("user").exclude(user=None):
        if not account.user.is_staff:
            account.user.password = make_password(None)
            account.user.save(update_fields=["password"])


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_rename_studenttab_account'),
    ]

    operations = [
        migrations.RunPython(require_nsid_login_for_existing_accounts, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['user__username', 'last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="canteen_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name='account',
            name='student_id',
        ),
        migrations.AddField(
            model_name='account',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(invalidate_legacy_customer_passwords, migrations.RunPython.noop),
    ]
